### ISSUE TITLE
你好,我fork你的代码后,视频渲染的窗口不在桌面图标的后面是什么原因?

### ISSUE THREAD

**Issue by 690275538** [he55/DreamScene2#1]
请问下你的微信或怎么联系到你,一起讨论下QQ 690275538

**Comment by 690275538** [comment]
我现在已经把vlcplayer集成到代码里面了,可以播放很多格式的视频.

**Comment by he55** [comment]
你需要设置视频渲染窗口的父窗口为桌面窗口

**Comment by 690275538** [comment]
不行啊

**Comment by he55** [comment]
加你了

**Comment by 690275538** [comment]
没收到加我消息

**Comment by 690275538** [comment]
现在又找到窗口了,不知道这么回事我也没设置啥

**Comment by 690275538** [comment]
https://www.codeproject.com/Articles/856020/Draw-Behind-Desktop-Icons-in-Windows-plus
