### ISSUE TITLE
获取桌面句柄失败

### ISSUE THREAD

**Issue by Leroy-X** [he55/DreamScene2#10]
你好，我下载的net472-x64的压缩包，运行时提示获取桌面句柄失败，win10 64
![00](https://user-images.githubusercontent.com/13515498/158167808-d6a03f9b-9b74-41fd-8908-c12bcbebedaf.png)

**Comment by Zerroi** [comment]
我也是啊

**Comment by LzwCracker** [comment]
win11 无法获取桌面句柄

**Comment by Apriqi** [comment]
我的win10也是这样

**Comment by Apriqi** [comment]
win10 运行后黑屏

**Comment by qidouhai** [comment]
我也是

**Comment by H402861965** [comment]
win11

**Comment by he55** [comment]
如果遇到获取桌面句柄失败，看看有没有安装其他桌面美化软件，关掉美化软件重启后试试。

**Comment by Kevin-Lewis1** [comment]
同问题，电脑上没有安装其他类似软件，Win11 22H2，试过重启后也是同样的问题

**Comment by he55** [comment]
打开高级系统设置->性能设置->视觉效果，选择第一个或者第二个选项
![1](https://github.com/he55/DreamScene2/assets/40764272/8ba69dc2-b0c3-414a-9745-82b0168296c5)

**Comment by he55** [comment]
> 同问题，电脑上没有安装其他类似软件，Win11 22H2，试过重启后也是同样的问题

试试这个方法 https://github.com/he55/DreamScene2/issues/10#issuecomment-1629950830

**Comment by Kevin-Lewis1** [comment]
> > 同问题，电脑上没有安装其他类似软件，Win11 22H2，试过重启后也是同样的问题
> 
> 试试这个方法 [#10 (comment)](https://github.com/he55/DreamScene2/issues/10#issuecomment-1629950830)

感谢！确实，我仅仅把“窗口内的动画控件和元素”打开，就可以正常使用了
