### ISSUE TITLE
两个显示器的话，只能设置成功一个显示器

### ISSUE THREAD

**Issue by BoyFaceGirl** [he55/DreamScene2#11]
如果有两个显示器的话，设置只能在一个显示器上有效果，这个问题怎么解决？

**Comment by he55** [comment]
因为性能考虑，目前只支持其中一个显示器设置动态桌面。

**Comment by BoyFaceGirl** [comment]
> 因为性能考虑，目前只支持其中一个显示器设置动态桌面。

我是个半吊子程序员，想研究一下您的代码也不知道该从哪里入手啊，惭愧。特别是DS2Native c++代码，看的头大。
        PInvoke.DS2_SetWindowPosition(hWnd, _screen.Bounds.ToRECT());
        PInvoke.SetParent(hWnd, _desktopWindowHandle); 
这两句代码是不是就是设置桌面的关键？设置自定义窗体的大小和位置后，将自定义窗口设置为系统窗口的子窗口？另外DS2Native代码怎么编译成为dll？

**Comment by he55** [comment]
对，是这两行代码。Visual Studio 安装 C++ 环境编译 DS2Native。
