### ISSUE TITLE
能实现支持否支持锁屏动画？

### ISSUE THREAD

**Issue by BoyFaceGirl** [he55/DreamScene2#15]
win8+以上的系统锁屏比较特殊，目前没找到相关的api来修改锁频壁纸的。我就是想解决这个锁屏问题找到的您的项目，希望大神能指点迷津，也希望您这个软件能实现这个功能。

**Comment by Quandong-Zhang** [comment]
不能，因为原理是再桌面窗口中的子窗口里插入窗口句柄。。
锁屏窗口我没记错的话应该没有子窗口吧

**Comment by BoyFaceGirl** [comment]
> 不能，因为原理是再桌面窗口中的子窗口里插入窗口句柄。。 锁屏窗口我没记错的话应该没有子窗口吧

有没有研究过类似锁屏聚焦这个功能？如果不用播放视频，动态切换自定义图片也很方便的。我研究好久没发现如何动态修改锁屏壁纸
