### ISSUE TITLE
WIN10 20H2 打开闪退

### ISSUE THREAD

**Issue by zyf7749qw** [he55/DreamScene2#16]
上一周还用的好好的，后面设置了开机启动，今天突然发现背景不会动了，然后看了下进程发现程序没有运行，手动运行的话进程会出现一下然后瞬间又没掉，不知道什么原因导致的

**Comment by he55** [comment]
背景不会动了。是不是动态桌面被暂停了。

**Comment by zyf7749qw** [comment]
> 背景不会动了。是不是动态桌面被暂停了。

不是哦，是整个软件进程都被关掉了，然后我再去打开就打不开了，就是打开没有反应，去任务管理局进程里面看就一闪而过，感觉一打开就被杀掉了
