### ISSUE TITLE
Windows 11 21H2 不能播放

### ISSUE THREAD

**Issue by flaging** [he55/DreamScene2#17]
我之前一直在用wallpaper engine,那天发现了咱们这个软件,就下载安装了,是可以播放的,但是在我卸载或者关闭wallpaper engine的时候咱们的软件就不能播放,这是什么问题呀???

**Comment by he55** [comment]
可以试试这个方法 https://github.com/he55/DreamScene2/issues/9#issuecomment-1068747639

**Comment by flaging** [comment]
> 可以试试这个方法 [#9 (comment)](https://github.com/he55/DreamScene2/issues/9#issuecomment-1068747639)

windows media player原本就安装了,我重新安装.net 6 也没有效果

**Comment by Quandong-Zhang** [comment]
> > 可以试试这个方法 [#9 (comment)](https://github.com/he55/DreamScene2/issues/9#issuecomment-1068747639)
> 
> windows media player原本就安装了,我重新安装.net 6 也没有效果

win11开始我也被坑了，发现给program manager 发那个消息不好使。。
不过好消息是，win11似乎不发消息也能把分出3层窗口这事发扬光大，它被用在了win11新增的多桌面功能上。你可以随便增加一个桌面之后再试，总之就是让系统调用下多桌面功能。

**Comment by flaging** [comment]
> > > 可以试试这个方法 [#9 (comment)](https://github.com/he55/DreamScene2/issues/9#issuecomment-1068747639)
> > 
> > 
> > windows media player原本就安装了,我重新安装.net 6 也没有效果
> 
> win11开始我也被坑了，发现给program manager 发那个消息不好使。。 不过好消息是，win11似乎不发消息也能把分出3层窗口这事发扬光大，它被用在了win11新增的多桌面功能上。你可以随便增加一个桌面之后再试，总之就是让系统调用下多桌面功能。

hihi 你是怎么解决的呀,我在调出新的桌面的时候会动一下,然后就不动了....

**Comment by flaging** [comment]
我找到问题的原因了, 是我还安装了腾讯桌面整理那个软件,把这个软件退出,咱们的动态桌面就可以运行了,感谢两位大佬

> > > > 可以试试这个方法 [#9 (comment)](https://github.com/he55/DreamScene2/issues/9#issuecomment-1068747639)
> > > 
> > > 
> > > windows media player原本就安装了,我重新安装.net 6 也没有效果
> > 
> > 
> > win11开始我也被坑了，发现给program manager 发那个消息不好使。。 不过好消息是，win11似乎不发消息也能把分出3层窗口这事发扬光大，它被用在了win11新增的多桌面功能上。你可以随便增加一个桌面之后再试，总之就是让系统调用下多桌面功能。
> 
> hihi 你是怎么解决的呀,我在调出新的桌面的时候会动一下,然后就不动了....
