### ISSUE TITLE
【BUG】与 DeskGo 同时时运行无法生效

### ISSUE THREAD

**Issue by KaRuiqin** [he55/DreamScene2#19]
最近发现了大佬的项目很感兴趣，但似乎在我的设备无法生效，
截止到本issue创建我使用的是 Windows 11 的最新的版本。

具体表现为：

1. 打开文件
2. 选择了一个正常的mp4文件
3. （没有反应）
4.  尝试点击 播放/暂停 按钮
5. （没有反应）

以下是我的`系统规格`
- 版本	Windows 11 专业工作站版
- 版本	21H2
- 操作系统版本	22000.593
- 体验	Windows 功能体验包 1000.22000.593.0

**Comment by Achley-233** [comment]
刚刚又测试了一下，是和 DeskGo 冲突了（
DeskGo 之前和 Wallpaper Engine 同时运行并不会冲突，所以一开始我没想到。

**Comment by Liuxxxx613** [comment]
可以换小智桌面，可以同时运行

**Comment by Achley-233** [comment]
![image](https://user-images.githubusercontent.com/69111766/168292660-96f1abed-c0d0-49d2-8558-992afdb70d84.png)


> 可以换小智桌面，可以同时运行

看了看它的官网..感觉还不如用腾讯的产品（

**Comment by JniTaim** [comment]
> ![image](https://user-images.githubusercontent.com/69111766/168292660-96f1abed-c0d0-49d2-8558-992afdb70d84.png)
> 
> > 可以换小智桌面，可以同时运行
> 
> 看了看它的官网..感觉还不如用腾讯的产品（

试试酷呆桌面https://www.coodesker.com/

**Comment by Achley-233** [comment]
> > ![image](https://user-images.githubusercontent.com/69111766/168292660-96f1abed-c0d0-49d2-8558-992afdb70d84.png)
> > > 可以换小智桌面，可以同时运行
> > 
> > 
> > 看了看它的官网..感觉还不如用腾讯的产品（
> 
> 试试酷呆桌面https://www.coodesker.com/

就网站上的介绍来看似乎起来不错捏
不够在那之后已经找到DeskGo 的替代品了：[Fences](https://www.stardock.com/products/fences/)
就目前我用了三个多月来看还是挺稳定的，而且功能也很多。

如果 @he55 大佬不打算试着兼容的话请关闭这个issue吧（~披萨厂也不配~），至少我这里已经没问题了。
大佬的项目就纯视频壁纸方面相比 Wallpaper Engine 好的不是一点半点（

**Comment by he55** [comment]
感谢支持。我没有找到修复的方法
