### ISSUE TITLE
使用一段时间后无法启动了

### ISSUE THREAD

**Issue by MagicnightGalaxy** [he55/DreamScene2#22]
win10，21H1，前段时间一直用的好好的，之前某一天开机不会自启了，手动打开也没有反应，从任务管理器看后台只会短暂出现几秒，然后就自动消失了

**Comment by MagicnightGalaxy** [comment]
在everything文件搜索工具里搜索DreamScene2会发现C盘-ProgramData-Microsoft-Windows-WER-ReportArchive路径会有AppCrash_DreamScene2.exe

**Comment by he55** [comment]
下载一个最新版试试

**Comment by MagicnightGalaxy** [comment]
> 下载一个最新版试试
releases里的net472-×64或net6.0-windows-×64是最新版吗

**Comment by he55** [comment]
是的

**Comment by MagicnightGalaxy** [comment]
这三天里又是百度又是必应不断搜索了各种appcrash怎么解决的办法，用任务管理器、控制面板、其他系统设置跟着各种搜索结果不断尝试 卸载了两个可能没啥关系的运行库.......不论怎么尝试，最后双击dreamscene2.exe就只有光标旁不争气的小圈转了两下，C盘的崩溃记录里悄然生成一个新的文件夹。最后也就在刚才实在是累了，一口气用everything搜索所有电脑里的所有dreamscene2和net476之类的相关文件，然后重启电脑再解压出来一份之前数次尝试时就已经下好的，删除时特意留下的唯一一份最新版本压缩包，可算是能打开了。难道appcrash就是的原因就是本地的dreamscene2太多了吗，至少现在是不太想追究了，能正常启动动态壁纸终于是舒了口气。最后还是对开发了这个项目的您说一声 谢谢（。＾▽＾）
