### ISSUE TITLE
[Bug]UI错误

### ISSUE THREAD

**Issue by HundSimon** [he55/DreamScene2#26]
### UI错误
**Code Version 1.5**
**Windows 10  x86**

启动时UI正常
打开任意文件后UI界面缩小
如下图
![after](https://user-images.githubusercontent.com/77706174/177999050-78af2307-b3b9-4bb0-a57b-8b69795199bd.png)
![before](https://user-images.githubusercontent.com/77706174/177999174-377882e0-ed96-42e7-aa82-5a81650d9da8.png)

**Comment by he55** [comment]
已经修复这个问题，Release 版已经更新
