### ISSUE TITLE
获取桌面句柄失败？

### ISSUE THREAD

**Issue by H402861965** [he55/DreamScene2#28]
获取桌面句柄失败？

**Comment by he55** [comment]
有安装其他桌面美化软件吗？

**Comment by H402861965** [comment]
> 



> 有安装其他桌面美化软件吗？

哈哈哈 果然关掉360桌面就好了

**Comment by he55** [comment]
好用 GitHub 给个星星支持一下

**Comment by pyhabyss** [comment]
同一个问题，然后我没有装任何的美化软件和杀毒软件...重启电脑只有系统进程的情况下也是获取句柄失败= =

**Comment by he55** [comment]
> 同一个问题，然后我没有装任何的美化软件和杀毒软件...重启电脑只有系统进程的情况下也是获取句柄失败= =

是什么系统

**Comment by DavidpYau** [comment]
win7，无美化软件，也是这样显示

**Comment by he55** [comment]
> win7，无美化软件，也是这样显示

没有适配 win7 系统😂

**Comment by Patchouli0609** [comment]
> 获取桌面句柄失败
解决方法：此电脑右键点属性，找到[高级系统设置])，点进去，在点性能的设置，进去后下面的框内有一个叫窗口内的动画控件和元素，把这个打上钩，然后点应用，点确定。
来自b站用户@3416510931

**Comment by TheWheel-s** [comment]
Win11 24H2 也显示获取桌面句柄失败
