### ISSUE TITLE
获取桌面句柄失败-bug

### ISSUE THREAD

**Issue by zq2hot** [he55/DreamScene2#30]
![2](https://user-images.githubusercontent.com/111860640/186118857-cc1ef883-6aa3-45f1-9509-613894e094fc.jpg)
![1](https://user-images.githubusercontent.com/111860640/186118871-0b0f0088-4d8f-41a9-b5c0-e37da26ee36c.jpg)

**Comment by he55** [comment]
有安装其他桌面美化软件吗？如果有关掉试试

**Comment by zq2hot** [comment]
我没安装其他桌面优化和桌面美化软件，然后我下载了一个lively wallpaper这个代替使用，在安装完这个软件后，我意外的发现，这个软件安装好了以后，DreamScane2居然可以用了，我怀疑是不是有某些相关运行库没有安装上才导致的获取桌面句柄失败？

> 有安装其他桌面美化软件吗？如果有关掉试试

我没安装其他桌面优化和桌面美化软件，然后我下载了一个lively wallpaper这个代替使用，在安装完这个软件后，我意外的发现，这个软件安装好了以后，DreamScane2居然可以用了，我怀疑是不是有某些相关运行库没有安装上才导致的获取桌面句柄失败？

**Comment by zq2hot** [comment]
希望在加入一个文件夹内壁纸定时自动轮换功能啊

**Comment by xkonglong** [comment]
我也是ltsc， 没有安装任何其他桌面美化软件。 也是提示获取桌面句柄失败

**Comment by he55** [comment]
> 我也是ltsc， 没有安装任何其他桌面美化软件。 也是提示获取桌面句柄失败

试试这个方法 https://github.com/he55/DreamScene2/issues/10#issuecomment-1629950830
