### ISSUE TITLE
SetParent 失败

### ISSUE THREAD

**Issue by dmhai** [he55/DreamScene2#37]
编译环境：win10 1903 + vs2022 17.3.6 

问题描述：直接从 https://github.com/he55/DreamScene2/releases 下载1.6的 releases包 和源码包，releases包可以正常使用，源码包编译后不可用。

问题详情：用vs2022打开工程，不做任何改动直接编译，然后把生成的 DS2Native.dll 拷贝到DreamScene2.exe ，运行exe，打开mp4文件，播放窗口自动全屏(遮盖所有东西，包括任务栏)，用spy++看了，VideoWindow 窗口不在 WorkerW 下面，应该是 SetParent 失败了

额外调试：基于[Releases包]可用的前提，从vs2022编译出文件做替换测试
1、 编译DS2Native.dll        替换到[Releases包]  = 不可用     => 编译的DS2Native.dll有问题
2、 编译DreamScene2.exe 替换到[Releases包]  = 不可用     => 编译的DreamScene2.exe有问题

所以，应该是我编译环境有问题，导致编译出来的dll和exe都不可用？还差了什么设置？

**Comment by he55** [comment]
不需要什么额外设置。你电脑有安装其他桌面美化软件吗，可以关了试试

**Comment by dmhai** [comment]
有，但是我都关了，应该没影响了。上面有说，用你编译出来的 net462.zip 里面的文件是正常的。 只是我自己编译的exe不能用，设置父窗口失败。
