### ISSUE TITLE
提供的Hiyori无法运行

### ISSUE THREAD

**Issue by shadowman2022** [he55/DreamScene2#38]
如图（这是在浏览器运行的结果）
![Snipaste_2022-12-21_18-01-56](https://user-images.githubusercontent.com/98646778/208877919-423f33bb-1604-48df-981e-1e1a79acdfa2.png)
DevTools中的结果
![Snipaste_2022-12-21_18-04-09](https://user-images.githubusercontent.com/98646778/208878315-3f917210-8a9e-48b7-9afc-05f5e23e0bff.png)

**Comment by he55** [comment]
直接在浏览器运行需要关闭跨域

**Comment by he55** [comment]
DreamScene2 设置方法 https://www.cnblogs.com/he55/p/15705047.html

**Comment by shadowman2022** [comment]
感谢！
