### ISSUE TITLE
希望能移除开机弹窗和隐藏托盘图标开关

### ISSUE THREAD

**Issue by webees** [he55/DreamScene2#39]
1、【BUG】建议去除网页不存在时的弹窗报错（try catch 空处理所有异常）
2、【优化】配置文件存放于程序所在目录（便于移动）
3、【优化】软件启动闪白屏问题，建议网页载入完成再显示，或增加可调节延时显示
4、【优化】推荐使用[WebView2 运行时](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)
5、【功能】如果还能调节web框架所在的区域面积和位置最好，这样可以变成一个便签或小窗体，就能多开软件调整web窗不同的位置，你可以同时看电影或者浏览其他网页

我的应用场景为网吧桌面通知、广告、背景壁纸、便签。

**Comment by he55** [comment]
我会修复bug。网页播放用的是 WebView2

**Comment by webees** [comment]
能够有开关打开窗体边框，手动调整大小和位置后，再关闭边框么？就有点像小组件了。
