### ISSUE TITLE
内存消耗

### ISSUE THREAD

**Issue by HX-Hendrix** [he55/DreamScene2#4]
如果采用视频播放，内存消耗问题是个重点。

**Comment by he55** [comment]
目前视频播放是使用 Windows 自带的解码器。如果有显卡，支持显卡解码视频。我之前遇到过一种情况，在没有显卡驱动的情况下会比较消耗内存和 CPU。能详细描述一下你遇到的情况吗。

**Comment by he55** [comment]
我在后续版本将增加 ffmpeg 视频播放引擎。

**Comment by HX-Hendrix** [comment]
使用的角度：
1.没有播放视频的情况下内存消耗：24.8M，选择播放56M的视频后，内存消耗增加到570-600+M上下浮动，稳定在610以内波动，感觉内存有上涨的趋势；
2.642M的视频，内存消耗265M，基本稳定变化不大，内存有很小的持续波动增长。
24.8M的视频 帧宽度、帧高度、数据速率、总比特率都比较大。
