### ISSUE TITLE
当存在主屏和副屏时，显示画面在两屏幕中间

### ISSUE THREAD

**Issue by asksuperboy** [he55/DreamScene2#40]
副屏16:9竖起，主屏32:9横向，当选择显示在主屏时，画面却出现在两个屏幕的中间位置，切换到副屏正常。

**Comment by he55** [comment]
我只有一个显示器，这个问题我不好重现。如果你有兴趣，你可以 Fork 我的代码在本地调试一下应该就可以找到问题
