### ISSUE TITLE
能否‘记忆’上次选择的路径。

### ISSUE THREAD

**Issue by ZYF-coder** [he55/DreamScene2#41]
能不能实现下让它可以‘记忆’上次选择的视频文件的路径？如此一来就能省去每次开机重新选择的步骤了。搭配Shell:SaterUp就能实现开自动打开视频，不弹出选择窗口。即开机自启。

**Comment by he55** [comment]
OK 我会加上这个功能。你可以点个星星或者 Fork 这个项目，下次更新功能你就知道了

**Comment by he55** [comment]
我新增加了命令行播放的支持 `DreamScene2.exe --background "视频文件路径"`，可以实现自定义功能功能

**Comment by ZYF-coder** [comment]
ok，我去试试
