### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by k4641321** [he55/DreamScene2#43]
在第一次使用时，会有几率视频播放的窗口在图标及任务栏前面（可能表达不清楚），并且在大屏显示器上，如希沃，视频无法适应显示器大小，播放时只显示了左上角的部分，希望作者大大能修一下

**Comment by k4641321** [comment]
还有一个，就是播放视频时的videowindow的窗口能不能做到不会在alt+tab时出现，如果可以，希望作者大大可以改改

**Comment by he55** [comment]
我在2k分辨率和高缩放比模式有测试，这种情况可能和系统软件环境有关，和其他桌面美化软件有冲突

**Comment by he55** [comment]
你的显示器分辨率是多少。alt+tab 我下个版本会优化，你可以Star或Fork项目，有更新你会知道

**Comment by k4641321** [comment]
分辨率应该是：3840x2160 当时闲着没事在班上的seewo下载下来玩，偶然发现了这个Bug，系统环境的话，系统是seewo魔改windows系统，因为发现自带的windows功能被删了

> 我在2k分辨率和高缩放比模式有测试，这种情况可能和系统软件环境有关，和其他桌面美化软件有冲突

**Comment by k4641321** [comment]
好奇问一下，视频使用什么播放的，能做到软件那么小，不会真的是HTML吧

**Comment by he55** [comment]
视频播放用的系统组件性能好，但支持的格式有限。HTML5用的WebView2
