### ISSUE TITLE
大哥下载了hiyori，结果里面没有应用程序呀，咋用呀

### ISSUE THREAD

**Issue by 13026698206** [he55/DreamScene2#44]
![image](https://github.com/he55/DreamScene2/assets/97940961/4090af17-bd60-4046-9178-d7192e785467)

**Comment by he55** [comment]
设置方法看这里 https://b23.tv/NCrWH1g 有用记得GitHub点个星星

**Comment by he55** [comment]
最新版支持文件拖拽播放，把html文件或者视频文件拖到软件上就可以打开文件
