### ISSUE TITLE
软件bug

### ISSUE THREAD

**Issue by Adoretheall007** [he55/DreamScene2#49]
当使用win+tab打开多桌面窗口时，软件会直接崩溃，动态壁纸不会再显示，但是当系统处于屏幕录制阶段时，却不会崩溃

**Comment by he55** [comment]
是Windows10 还是Windows11系统

**Comment by Adoretheall007** [comment]
可是能软件冲突了，他现在不会出现崩溃了

**Comment by augviolet** [comment]
我是win10也出现这个问题了

**Comment by augviolet** [comment]
> 我是win10也出现这个问题了。而且也会连带着把其他所有windows美化的软件也搞崩溃掉，比如taskbarx。还有一个问题就是，有时候强行在任务管理器结束任务会很容易卡住，不是系统卡住，就是桌面背景卡住了动态壁纸的一帧

taskbarx应该是由于dreamscene2崩溃，导致重启了资源管理器，所以掉线了。这个玩意是有这问题。。

**Comment by he55** [comment]
> 我是win10也出现这个问题了。而且也会连带着把其他所有windows美化的软件也搞崩溃掉，比如taskbarx。还有一个问题就是，有时候强行在任务管理器结束任务会很容易卡住，不是系统卡住，就是桌面背景卡住了动态壁纸的一帧

强制结束程序会有这个问题。这种情况手动重新设置一下桌面壁纸，桌面显示就正常了。taskbarx我没有用过，是什么原因导致崩溃的暂时不清楚。

**Comment by 6Tom** [comment]
+1，win+tab必崩溃，未使用其他美化软件，win11 专业版 22621.3296
