### ISSUE TITLE
操作系统支持

### ISSUE THREAD

**Issue by Water-Melon** [he55/DreamScene2#6]
期待支持MacOS

**Comment by he55** [comment]
我会将支持 macOS 系统加入我的计划。

**Comment by 2439905184** [comment]
会考虑支持linux 和windows7 或者32位系统吗？

**Comment by Quandong-Zhang** [comment]
> 期待支持MacOS

恐怕不能，因为这个项目的实现利用了win窗口的子窗口特性，mac很可能没有

**Comment by he55** [comment]
> 会考虑支持linux 和windows7 或者32位系统吗？

编译一个 32 位的版本就可以支持 32 位系统。如果支持想 Windows 7 系统，就需要安装 .NET Framework 4.7.2 这对用户来说是件麻烦事情。Linux 我没有开发经验，macOS 的动态桌面我倒有研究。

**Comment by he55** [comment]
> > 期待支持MacOS
> 
> 恐怕不能，因为这个项目的实现利用了win窗口的子窗口特性，mac很可能没有

macOS 的动态桌面实现不复杂。我的另一个项目 macOS 命令行版本动态桌面 https://github.com/he55/AnimatedDesktop
