### ISSUE TITLE
win10无法播放MP4

### ISSUE THREAD

**Issue by foxfire2015** [he55/DreamScene2#9]
安装.net6后，依然是黑屏无法播放MP4文件；试过多个MP4文件；Hiyori.html可以正常播放

**Comment by dosin** [comment]
哥们 我的也是黑屏 然后我去控制面板\所有控制面板项\程序和功能\启用或关闭Windows功能那里把windows media player安装回来就可以播放了

**Comment by 6Tom** [comment]
我也是因为禁用了Windows media player导致黑屏，感谢dosin修好了现在

he55您可以在主页提一嘴这事
